name: examen_app
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: ">=2.16.1 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  cloud_firestore: ^1.0.0
  google_fonts: ^2.0.0
  provider: ^5.0.0
  cupertino_icons: ^1.0.2
  firebase_core: ^1.14.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  change_app_package_name: ^1.0.0


  flutter_lints: ^1.0.0


flutter:
  assets:
    - assets/

  uses-material-design: true


